# Documentation: https://roots.io/trellis/docs/remote-server-setup/
wordpress_sites:
  blueprint.dev:
    site_hosts:
      - leviathan.lemp.io
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:jbradach/blueprint-wp.git
    branch: master
    repo_subtree_path: site
    permalink_structure: "/%postname%/"
    multisite:
      enabled: false
	      subdomains: false
    ssl:
      enabled: true
      cert: /etc/letsencrypt/live/leviathan.lemp.io/fullchain.pem
      key:  /etc/letsencrypt/live/leviathan.lemp.io/privkey.pem
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: https://leviathan.lemp.io
      wp_siteurl: https://leviathan.lemp.io/wp
      wp_env: staging
      db_name: blueprint_staging
      db_user: blueprint_dbuser
      # Define the following variables in group_vars/staging/vault.yml
      # db_password:
      # auth_key:
      # secure_auth_key:
      # logged_in_key:
      # nonce_key:
      # auth_salt:
      # secure_auth_salt:
      # logged_in_salt:
      # nonce_salt:
